<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <title>Nobody’s</title>
  <!--=================================
  Meta tags
  =================================-->
  <meta name="description" content="Funkiwala Records Label represents unique music like British Afro-Jazz, Sufi Samba, Bengali Reggae, Cuban Funk, Mystic Dub, BanglaAfroLatinJazz etc." />
  <meta content="yes" name="apple-mobile-web-app-capable" />
  <meta name="viewport" content="minimum-scale=1.0, width=device-width, maximum-scale=1, user-scalable=no" />
  <link rel="icon" href="../../assets/images/favicon.ico" type="image/x-icon" />
  

  <!--=================================
  Style Sheets
  =================================-->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css" integrity="sha512-HK5fgLBL+xu6dm/Ii3z4xhlSUyZgTT9tuc/hSrtw6uzJOvgRr2a9jyxxT1ely+B+xFAmJKVSTbpM/CuL7qxO8w==" crossorigin="anonymous" />
  <link rel="stylesheet" href="../../dist/css/style.css" />
  <link rel="stylesheet" href="../../assets/mediaelement/build/mediaelementplayer.min.css" />


  <style>



  </style>
</head>

<body>

  <!--=========================
  Header
  ===========================-->

<?php include '../../assets/phpincludes/header.php'; ?>

<div class="intersection-observer container">
  <h1 class=albumo>Maurizio Ravalico - Nobody's Husband, Nobody's Dad</h1>


  <section class="album__flex">

    <div class="album__itemleft albumo__item">
      <img src="../../assets/images/albums/front/Nobody'sHusband,Nobody'sDad.jpg">


        <!-- <div class="audioplayer__item">
       
          <div class="audioplayer">
            <h3>Nobody's Husband, Nobody's Dad</h3>
            <audio class="mejs__player">
              <source src="../../assets/audio/Nobody'sHusband,Nobody'sDad.mp3" type="audio/mpeg" />
            </audio>
          </div>


         </div> -->

    </div>

    <div class="album__itemright albumo__item">

      <p>
        Funkiwala is proud to be the bearer of Maurizio Ravalico’s first full-length album, “Nobody’s Husband, Nobody’s Dad”, an intriguing, visionary and very unique percussion work, which is in his own words “the most eloquent synthesis to date of my lifelong love affair with percussion music”.
      </p>

      <p>
        The music on “Nobody’s Husband, Nobody’s Dad” is entirely acoustic and live played, with no overdubs and no electronic manipulations added to the initial takes. These have all been slightly edited to different degrees, mainly to fit them into the time limitations of vinyl; but other than that all tracks are faithful reproductions of single, unplugged, uninterrupted one-man performances.
      </p>

      <p>
        Another distinctive musical trait of the album is its persistent denial of metric recurrence. Maurizio’s solo music is focusing on sounds, often generated by unexpected combinations of conventional instruments and found objects, both played using a mix of orthodox and extended techniques, and often on top of a big drum, which augments dramatically their timbrical and tonal range. The finished pieces recall thus the aesthetics of both contemporary and improvised music, despite them being neither strictly composed nor at all improvised.
      </p>

      <p>
        The album is a meaty 180gsm piece of black first grade wax, coming in a sleeve complete of full-colour inner, and beautiful photos of Maurizio attired in a proto-sapiens fashion, courtesy of Alessandro 'Benni' Parlante, who incidentally is also responsible for the cover of Maurizio’s previous release, Fiium Shaarrk's We Are Astonishingly Lifelike (Not Applicable, 2017).
      </p>

      <br>
      <br>

      <p>
        “One of the finest avant-garde percussionists in the world. Maurizio Ravalico is incredible to watch and hear. Catch him live somewhere soon!”
        <br>
        Jean-Claude Thompson, IfMusic.co.uk
      </p>

      <p>
        “Creative, deep and intriguing. Percussion avantgarde at its best.”
        <br>
        Vince Vella, Dj, producer, Havana Cultura
      </p>

      <p>
        “When I grow up I want to be like Maurizio Ravalico.”
        <br>
        Axel Drioli, www.axeldrioli.com
      </p>

      <p>
        "Roger Turner would have been much more fun."
        <br>
        Dan Warburton, ParisTransatlantic.com
      </p>


      <div class="album__sociall">
        <a href="https://maurizioravalico.bandcamp.com/album/nobodys-husband-nobodys-dad" class="album__sociala" target="_blank">
          Bandcamp
        </a> 
        <a href="https://funkiwala.kudosrecords.co.uk/release/fwlp006/maurizio-ravalico-nobodys-husband-nobodys-dad" class="album__sociala" target="_blank">
        Kudos Records
        </a>  

      </div>

    </div>
</section>

 <a onclick="scrollTopAnimated()" class="scroll top">TOP</a>

  </div>
  <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
  <script src="../../assets/mediaelement/build//mediaelement-and-player.min.js"></script>
  <script src="../../assets/js/other.js" defer></script>
</body>